require(["config"],function(){
	require(["jquery","Public","listload","template"],function($,Public,list,template){
		$(function(){
			Public.init();
			list.listload(template);
			//list.init();
		})		
	})
})